import 'package:kojina_project/model/meal_model.dart';
import 'package:kojina_project/provider/base_provider.dart';

class MealsProvider extends BaseProvider {
  List<MealModel> meals = [
    MealModel(
      id: 1,
      kitchenId: 1,
      kitchenName: 'Italian Kitchen',
      mealName: 'Spaghetti Carbonara',
      mealDescription: 'Classic Italian pasta dish with creamy sauce and pancetta.',
      ingredients: ['Pasta', 'Eggs', 'Pancetta', 'Parmesan cheese', 'Black pepper'],
      mealImage: 'assets/meal1.png',
      price: 12,
      category: 'Italian',
      discount: null,
      rating: 4.5,
    ),
    MealModel(
      id: 2,
      kitchenId: 2,
      kitchenName: 'Indian Kitchen',
      mealName: 'Chicken Tikka Masala',
      mealDescription: 'Popular Indian curry dish with marinated chicken in a spiced tomato sauce.',
      ingredients: ['Chicken', 'Yogurt', 'Tomato', 'Onion', 'Garlic', 'Ginger', 'Spices'],
      mealImage: 'assets/meal1.png',
      price: 15,
      category: 'Indian',
      discount: 10,
      rating: 4.7,
    ),
    MealModel(
      id: 3,
      kitchenId: 1,
      kitchenName: 'Japanese Kitchen',
      mealName: 'Sushi Platter',
      mealDescription: 'Assorted sushi rolls with fresh fish, rice, and seaweed.',
      ingredients: ['Rice', 'Fish', 'Seaweed', 'Soy sauce', 'Wasabi', 'Pickled ginger'],
      mealImage: 'assets/meal1.png',
      price: 20,
      category: 'Japanese',
      discount: 5,
      rating: 4.8,
    ),
    MealModel(
      id: 4,
      kitchenId: 3,
      kitchenName: 'Mexican Kitchen',
      mealName: 'Beef Tacos',
      mealDescription: 'Mexican dish with seasoned beef, lettuce, cheese, and salsa in a tortilla.',
      ingredients: ['Beef', 'Tortilla', 'Lettuce', 'Cheese', 'Salsa'],
      mealImage: 'assets/meal1.png',
      price: 10,
      category: 'Mexican',
      discount: 2,
      rating: 4.3,
    ),
    MealModel(
      id: 5,
      kitchenId: 2,
      kitchenName: 'Thai Kitchen',
      mealName: 'Pad Thai',
      mealDescription: 'Stir-fried rice noodle dish with shrimp, peanuts, and bean sprouts.',
      ingredients: ['Rice noodles', 'Shrimp', 'Peanuts', 'Bean sprouts', 'Egg', 'Tamarind paste'],
      mealImage: 'assets/meal1.png',
      price: 14,
      category: 'Thai',
      discount: 3,
      rating: 4.6,
    ),
    MealModel(
      id: 6,
      kitchenId: 1,
      kitchenName: 'American Kitchen',
      mealName: 'Cheeseburger',
      mealDescription: 'Classic American burger with beef patty, cheese, lettuce, and tomato.',
      ingredients: ['Beef patty', 'Cheese', 'Lettuce', 'Tomato', 'Bun'],
      mealImage: 'assets/meal1.png',
      price: 8,
      category: 'American',
      discount: null,
      rating: 4.2,
    ),
    MealModel(
      id: 7,
      kitchenId: 3,
      kitchenName: 'Middle Eastern Kitchen',
      mealName: 'Falafel Wrap',
      mealDescription: 'Middle Eastern wrap with falafel, hummus, and vegetables.',
      ingredients: ['Falafel', 'Hummus', 'Lettuce', 'Tomato', 'Wrap'],
      mealImage: 'assets/meal1.png',
      price: 9,
      category: 'Middle Eastern',
      discount: 1,
      rating: 4.4,
    ),
    MealModel(
      id: 8,
      kitchenId: 2,
      kitchenName: 'Italian Kitchen',
      mealName: 'Margherita Pizza',
      mealDescription: 'Classic Italian pizza with tomato, mozzarella, and basil.',
      ingredients: ['Tomato', 'Mozzarella', 'Basil', 'Pizza dough'],
      mealImage: 'assets/meal1.png',
      price: 11,
      category: 'Italian',
      discount: 2,
      rating: 4.5,
    ),
    MealModel(
      id: 9,
      kitchenId: 1,
      kitchenName: 'Salad Kitchen',
      mealName: 'Caesar Salad',
      mealDescription: 'Salad with romaine lettuce, croutons, parmesan, and Caesar dressing.',
      ingredients: ['Romaine lettuce', 'Croutons', 'Parmesan', 'Caesar dressing'],
      mealImage: 'assets/meal1.png',
      price: 7,
      category: 'Salad',
      discount: null,
      rating: 4.1,
    ),
    MealModel(
      id: 10,
      kitchenId: 3,
      kitchenName: 'Japanese Kitchen',
      mealName: 'Ramen',
      mealDescription: 'Japanese noodle soup with broth, noodles, and various toppings.',
      ingredients: ['Broth', 'Noodles', 'Pork', 'Egg', 'Green onions'],
      mealImage: 'assets/meal1.png',
      price: 13,
      category: 'Japanese',
      discount: 4,
      rating: 4.7,
    ),
    MealModel(
      id: 11,
      kitchenId: 2,
      kitchenName: 'British Kitchen',
      mealName: 'Fish and Chips',
      mealDescription: 'British dish with battered fish and fried potatoes.',
      ingredients: ['Fish', 'Potatoes', 'Batter', 'Tartar sauce'],
      mealImage: 'assets/meal1.png',
      price: 12,
      category: 'British',
      discount: 2,
      rating: 4.3,
    ),
    MealModel(
      id: 12,
      kitchenId: 1,
      kitchenName: 'Greek Kitchen',
      mealName: 'Greek Salad',
      mealDescription: 'Salad with tomatoes, cucumbers, olives, feta cheese, and olive oil.',
      ingredients: ['Tomatoes', 'Cucumbers', 'Olives', 'Feta cheese', 'Olive oil'],
      mealImage: 'assets/meal1.png',
      price: 8,
      category: 'Greek',
      discount: 1,
      rating: 4.2,
    ),
    MealModel(
      id: 13,
      kitchenId: 3,
      kitchenName: 'Vietnamese Kitchen',
      mealName: 'Pho',
      mealDescription: 'Vietnamese noodle soup with broth, rice noodles, and herbs.',
      ingredients: ['Broth', 'Rice noodles', 'Beef', 'Herbs', 'Lime'],
      mealImage: 'assets/meal1.png',
      price: 14,
      category: 'Vietnamese',
      discount: 3,
      rating: 4.6,
    ),
    
    
  ];
}